# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'ActionType',
    'CustomRuleEnabledState',
    'ManagedRuleEnabledState',
    'ManagedRuleExclusionMatchVariable',
    'ManagedRuleExclusionSelectorMatchOperator',
    'ManagedRuleSetActionType',
    'MatchVariable',
    'Operator',
    'PolicyEnabledState',
    'PolicyMode',
    'PolicyRequestBodyCheck',
    'RuleType',
    'ScrubbingRuleEntryMatchOperator',
    'ScrubbingRuleEntryMatchVariable',
    'ScrubbingRuleEntryState',
    'SkuName',
    'TransformType',
    'VariableName',
    'WebApplicationFirewallScrubbingState',
]


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ActionType")
class ActionType(_builtins.str, Enum):
    """
    Describes the override action to be applied when rule matches.
    """
    ALLOW = "Allow"
    BLOCK = "Block"
    LOG = "Log"
    REDIRECT = "Redirect"
    ANOMALY_SCORING = "AnomalyScoring"
    JS_CHALLENGE = "JSChallenge"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:CustomRuleEnabledState")
class CustomRuleEnabledState(_builtins.str, Enum):
    """
    Describes if the custom rule is in enabled or disabled state. Defaults to Enabled if not specified.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ManagedRuleEnabledState")
class ManagedRuleEnabledState(_builtins.str, Enum):
    """
    Describes if the managed rule is in enabled or disabled state. Defaults to Disabled if not specified.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ManagedRuleExclusionMatchVariable")
class ManagedRuleExclusionMatchVariable(_builtins.str, Enum):
    """
    The variable type to be excluded.
    """
    REQUEST_HEADER_NAMES = "RequestHeaderNames"
    REQUEST_COOKIE_NAMES = "RequestCookieNames"
    QUERY_STRING_ARG_NAMES = "QueryStringArgNames"
    REQUEST_BODY_POST_ARG_NAMES = "RequestBodyPostArgNames"
    REQUEST_BODY_JSON_ARG_NAMES = "RequestBodyJsonArgNames"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ManagedRuleExclusionSelectorMatchOperator")
class ManagedRuleExclusionSelectorMatchOperator(_builtins.str, Enum):
    """
    Comparison operator to apply to the selector when specifying which elements in the collection this exclusion applies to.
    """
    EQUALS = "Equals"
    CONTAINS = "Contains"
    STARTS_WITH = "StartsWith"
    ENDS_WITH = "EndsWith"
    EQUALS_ANY = "EqualsAny"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ManagedRuleSetActionType")
class ManagedRuleSetActionType(_builtins.str, Enum):
    """
    Defines the rule set action.
    """
    BLOCK = "Block"
    LOG = "Log"
    REDIRECT = "Redirect"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:MatchVariable")
class MatchVariable(_builtins.str, Enum):
    """
    Request variable to compare with.
    """
    REMOTE_ADDR = "RemoteAddr"
    REQUEST_METHOD = "RequestMethod"
    QUERY_STRING = "QueryString"
    POST_ARGS = "PostArgs"
    REQUEST_URI = "RequestUri"
    REQUEST_HEADER = "RequestHeader"
    REQUEST_BODY = "RequestBody"
    COOKIES = "Cookies"
    SOCKET_ADDR = "SocketAddr"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:Operator")
class Operator(_builtins.str, Enum):
    """
    Comparison type to use for matching with the variable value.
    """
    ANY = "Any"
    IP_MATCH = "IPMatch"
    GEO_MATCH = "GeoMatch"
    EQUAL = "Equal"
    CONTAINS = "Contains"
    LESS_THAN = "LessThan"
    GREATER_THAN = "GreaterThan"
    LESS_THAN_OR_EQUAL = "LessThanOrEqual"
    GREATER_THAN_OR_EQUAL = "GreaterThanOrEqual"
    BEGINS_WITH = "BeginsWith"
    ENDS_WITH = "EndsWith"
    REG_EX = "RegEx"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:PolicyEnabledState")
class PolicyEnabledState(_builtins.str, Enum):
    """
    Describes if the policy is in enabled or disabled state. Defaults to Enabled if not specified.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:PolicyMode")
class PolicyMode(_builtins.str, Enum):
    """
    Describes if it is in detection mode or prevention mode at policy level.
    """
    PREVENTION = "Prevention"
    DETECTION = "Detection"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:PolicyRequestBodyCheck")
class PolicyRequestBodyCheck(_builtins.str, Enum):
    """
    Describes if policy managed rules will inspect the request body content.
    """
    DISABLED = "Disabled"
    ENABLED = "Enabled"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:RuleType")
class RuleType(_builtins.str, Enum):
    """
    Describes type of rule.
    """
    MATCH_RULE = "MatchRule"
    RATE_LIMIT_RULE = "RateLimitRule"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ScrubbingRuleEntryMatchOperator")
class ScrubbingRuleEntryMatchOperator(_builtins.str, Enum):
    """
    When matchVariable is a collection, operate on the selector to specify which elements in the collection this rule applies to.
    """
    EQUALS_ANY = "EqualsAny"
    EQUALS = "Equals"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ScrubbingRuleEntryMatchVariable")
class ScrubbingRuleEntryMatchVariable(_builtins.str, Enum):
    """
    The variable to be scrubbed from the logs.
    """
    REQUEST_IP_ADDRESS = "RequestIPAddress"
    REQUEST_URI = "RequestUri"
    QUERY_STRING_ARG_NAMES = "QueryStringArgNames"
    REQUEST_HEADER_NAMES = "RequestHeaderNames"
    REQUEST_COOKIE_NAMES = "RequestCookieNames"
    REQUEST_BODY_POST_ARG_NAMES = "RequestBodyPostArgNames"
    REQUEST_BODY_JSON_ARG_NAMES = "RequestBodyJsonArgNames"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:ScrubbingRuleEntryState")
class ScrubbingRuleEntryState(_builtins.str, Enum):
    """
    Defines the state of a log scrubbing rule. Default value is enabled.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:SkuName")
class SkuName(_builtins.str, Enum):
    """
    Name of the pricing tier.
    """
    CLASSIC_AZURE_FRONT_DOOR = "Classic_AzureFrontDoor"
    STANDARD_AZURE_FRONT_DOOR = "Standard_AzureFrontDoor"
    PREMIUM_AZURE_FRONT_DOOR = "Premium_AzureFrontDoor"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:TransformType")
class TransformType(_builtins.str, Enum):
    """
    Describes what transforms applied before matching.
    """
    LOWERCASE = "Lowercase"
    UPPERCASE = "Uppercase"
    TRIM = "Trim"
    URL_DECODE = "UrlDecode"
    URL_ENCODE = "UrlEncode"
    REMOVE_NULLS = "RemoveNulls"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:VariableName")
class VariableName(_builtins.str, Enum):
    """
    Describes the supported variable for group by
    """
    SOCKET_ADDR = "SocketAddr"
    GEO_LOCATION = "GeoLocation"
    NONE = "None"


@pulumi.type_token("azure-native_frontdoor_v20240201:frontdoor:WebApplicationFirewallScrubbingState")
class WebApplicationFirewallScrubbingState(_builtins.str, Enum):
    """
    State of the log scrubbing config. Default value is Enabled.
    """
    ENABLED = "Enabled"
    DISABLED = "Disabled"
