# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'CustomRuleListArgs',
    'CustomRuleListArgsDict',
    'CustomRuleArgs',
    'CustomRuleArgsDict',
    'GroupByVariableArgs',
    'GroupByVariableArgsDict',
    'ManagedRuleExclusionArgs',
    'ManagedRuleExclusionArgsDict',
    'ManagedRuleGroupOverrideArgs',
    'ManagedRuleGroupOverrideArgsDict',
    'ManagedRuleOverrideArgs',
    'ManagedRuleOverrideArgsDict',
    'ManagedRuleSetListArgs',
    'ManagedRuleSetListArgsDict',
    'ManagedRuleSetArgs',
    'ManagedRuleSetArgsDict',
    'MatchConditionArgs',
    'MatchConditionArgsDict',
    'PolicySettingsArgs',
    'PolicySettingsArgsDict',
    'SkuArgs',
    'SkuArgsDict',
    'WebApplicationFirewallScrubbingRulesArgs',
    'WebApplicationFirewallScrubbingRulesArgsDict',
]

class CustomRuleListArgsDict(TypedDict):
    """
    Defines contents of custom rules
    """
    rules: NotRequired[pulumi.Input[Sequence[pulumi.Input['CustomRuleArgsDict']]]]
    """
    List of rules
    """

@pulumi.input_type
class CustomRuleListArgs:
    def __init__(__self__, *,
                 rules: Optional[pulumi.Input[Sequence[pulumi.Input['CustomRuleArgs']]]] = None):
        """
        Defines contents of custom rules

        :param pulumi.Input[Sequence[pulumi.Input['CustomRuleArgs']]] rules: List of rules
        """
        if rules is not None:
            pulumi.set(__self__, "rules", rules)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['CustomRuleArgs']]]]:
        """
        List of rules
        """
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['CustomRuleArgs']]]]):
        pulumi.set(self, "rules", value)


class CustomRuleArgsDict(TypedDict):
    """
    Defines contents of a web application rule
    """
    action: pulumi.Input[Union[_builtins.str, 'ActionType']]
    """
    Describes what action to be applied when rule matches.
    """
    match_conditions: pulumi.Input[Sequence[pulumi.Input['MatchConditionArgsDict']]]
    """
    List of match conditions.
    """
    priority: pulumi.Input[_builtins.int]
    """
    Describes priority of the rule. Rules with a lower value will be evaluated before rules with a higher value.
    """
    rule_type: pulumi.Input[Union[_builtins.str, 'RuleType']]
    """
    Describes type of rule.
    """
    enabled_state: NotRequired[pulumi.Input[Union[_builtins.str, 'CustomRuleEnabledState']]]
    """
    Describes if the custom rule is in enabled or disabled state. Defaults to Enabled if not specified.
    """
    group_by: NotRequired[pulumi.Input[Sequence[pulumi.Input['GroupByVariableArgsDict']]]]
    """
    Describes the list of variables to group the rate limit requests
    """
    name: NotRequired[pulumi.Input[_builtins.str]]
    """
    Describes the name of the rule.
    """
    rate_limit_duration_in_minutes: NotRequired[pulumi.Input[_builtins.int]]
    """
    Time window for resetting the rate limit count. Default is 1 minute.
    """
    rate_limit_threshold: NotRequired[pulumi.Input[_builtins.int]]
    """
    Number of allowed requests per client within the time window.
    """

@pulumi.input_type
class CustomRuleArgs:
    def __init__(__self__, *,
                 action: pulumi.Input[Union[_builtins.str, 'ActionType']],
                 match_conditions: pulumi.Input[Sequence[pulumi.Input['MatchConditionArgs']]],
                 priority: pulumi.Input[_builtins.int],
                 rule_type: pulumi.Input[Union[_builtins.str, 'RuleType']],
                 enabled_state: Optional[pulumi.Input[Union[_builtins.str, 'CustomRuleEnabledState']]] = None,
                 group_by: Optional[pulumi.Input[Sequence[pulumi.Input['GroupByVariableArgs']]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rate_limit_duration_in_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 rate_limit_threshold: Optional[pulumi.Input[_builtins.int]] = None):
        """
        Defines contents of a web application rule

        :param pulumi.Input[Union[_builtins.str, 'ActionType']] action: Describes what action to be applied when rule matches.
        :param pulumi.Input[Sequence[pulumi.Input['MatchConditionArgs']]] match_conditions: List of match conditions.
        :param pulumi.Input[_builtins.int] priority: Describes priority of the rule. Rules with a lower value will be evaluated before rules with a higher value.
        :param pulumi.Input[Union[_builtins.str, 'RuleType']] rule_type: Describes type of rule.
        :param pulumi.Input[Union[_builtins.str, 'CustomRuleEnabledState']] enabled_state: Describes if the custom rule is in enabled or disabled state. Defaults to Enabled if not specified.
        :param pulumi.Input[Sequence[pulumi.Input['GroupByVariableArgs']]] group_by: Describes the list of variables to group the rate limit requests
        :param pulumi.Input[_builtins.str] name: Describes the name of the rule.
        :param pulumi.Input[_builtins.int] rate_limit_duration_in_minutes: Time window for resetting the rate limit count. Default is 1 minute.
        :param pulumi.Input[_builtins.int] rate_limit_threshold: Number of allowed requests per client within the time window.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "match_conditions", match_conditions)
        pulumi.set(__self__, "priority", priority)
        pulumi.set(__self__, "rule_type", rule_type)
        if enabled_state is not None:
            pulumi.set(__self__, "enabled_state", enabled_state)
        if group_by is not None:
            pulumi.set(__self__, "group_by", group_by)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rate_limit_duration_in_minutes is not None:
            pulumi.set(__self__, "rate_limit_duration_in_minutes", rate_limit_duration_in_minutes)
        if rate_limit_threshold is not None:
            pulumi.set(__self__, "rate_limit_threshold", rate_limit_threshold)

    @_builtins.property
    @pulumi.getter
    def action(self) -> pulumi.Input[Union[_builtins.str, 'ActionType']]:
        """
        Describes what action to be applied when rule matches.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input[Union[_builtins.str, 'ActionType']]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="matchConditions")
    def match_conditions(self) -> pulumi.Input[Sequence[pulumi.Input['MatchConditionArgs']]]:
        """
        List of match conditions.
        """
        return pulumi.get(self, "match_conditions")

    @match_conditions.setter
    def match_conditions(self, value: pulumi.Input[Sequence[pulumi.Input['MatchConditionArgs']]]):
        pulumi.set(self, "match_conditions", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> pulumi.Input[_builtins.int]:
        """
        Describes priority of the rule. Rules with a lower value will be evaluated before rules with a higher value.
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter(name="ruleType")
    def rule_type(self) -> pulumi.Input[Union[_builtins.str, 'RuleType']]:
        """
        Describes type of rule.
        """
        return pulumi.get(self, "rule_type")

    @rule_type.setter
    def rule_type(self, value: pulumi.Input[Union[_builtins.str, 'RuleType']]):
        pulumi.set(self, "rule_type", value)

    @_builtins.property
    @pulumi.getter(name="enabledState")
    def enabled_state(self) -> Optional[pulumi.Input[Union[_builtins.str, 'CustomRuleEnabledState']]]:
        """
        Describes if the custom rule is in enabled or disabled state. Defaults to Enabled if not specified.
        """
        return pulumi.get(self, "enabled_state")

    @enabled_state.setter
    def enabled_state(self, value: Optional[pulumi.Input[Union[_builtins.str, 'CustomRuleEnabledState']]]):
        pulumi.set(self, "enabled_state", value)

    @_builtins.property
    @pulumi.getter(name="groupBy")
    def group_by(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['GroupByVariableArgs']]]]:
        """
        Describes the list of variables to group the rate limit requests
        """
        return pulumi.get(self, "group_by")

    @group_by.setter
    def group_by(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['GroupByVariableArgs']]]]):
        pulumi.set(self, "group_by", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Describes the name of the rule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rateLimitDurationInMinutes")
    def rate_limit_duration_in_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Time window for resetting the rate limit count. Default is 1 minute.
        """
        return pulumi.get(self, "rate_limit_duration_in_minutes")

    @rate_limit_duration_in_minutes.setter
    def rate_limit_duration_in_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rate_limit_duration_in_minutes", value)

    @_builtins.property
    @pulumi.getter(name="rateLimitThreshold")
    def rate_limit_threshold(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of allowed requests per client within the time window.
        """
        return pulumi.get(self, "rate_limit_threshold")

    @rate_limit_threshold.setter
    def rate_limit_threshold(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "rate_limit_threshold", value)


class GroupByVariableArgsDict(TypedDict):
    """
    Describes the variables available to group the rate limit requests
    """
    variable_name: pulumi.Input[Union[_builtins.str, 'VariableName']]
    """
    Describes the supported variable for group by
    """

@pulumi.input_type
class GroupByVariableArgs:
    def __init__(__self__, *,
                 variable_name: pulumi.Input[Union[_builtins.str, 'VariableName']]):
        """
        Describes the variables available to group the rate limit requests

        :param pulumi.Input[Union[_builtins.str, 'VariableName']] variable_name: Describes the supported variable for group by
        """
        pulumi.set(__self__, "variable_name", variable_name)

    @_builtins.property
    @pulumi.getter(name="variableName")
    def variable_name(self) -> pulumi.Input[Union[_builtins.str, 'VariableName']]:
        """
        Describes the supported variable for group by
        """
        return pulumi.get(self, "variable_name")

    @variable_name.setter
    def variable_name(self, value: pulumi.Input[Union[_builtins.str, 'VariableName']]):
        pulumi.set(self, "variable_name", value)


class ManagedRuleExclusionArgsDict(TypedDict):
    """
    Exclude variables from managed rule evaluation.
    """
    match_variable: pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionMatchVariable']]
    """
    The variable type to be excluded.
    """
    selector: pulumi.Input[_builtins.str]
    """
    Selector value for which elements in the collection this exclusion applies to.
    """
    selector_match_operator: pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionSelectorMatchOperator']]
    """
    Comparison operator to apply to the selector when specifying which elements in the collection this exclusion applies to.
    """

@pulumi.input_type
class ManagedRuleExclusionArgs:
    def __init__(__self__, *,
                 match_variable: pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionMatchVariable']],
                 selector: pulumi.Input[_builtins.str],
                 selector_match_operator: pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionSelectorMatchOperator']]):
        """
        Exclude variables from managed rule evaluation.

        :param pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionMatchVariable']] match_variable: The variable type to be excluded.
        :param pulumi.Input[_builtins.str] selector: Selector value for which elements in the collection this exclusion applies to.
        :param pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionSelectorMatchOperator']] selector_match_operator: Comparison operator to apply to the selector when specifying which elements in the collection this exclusion applies to.
        """
        pulumi.set(__self__, "match_variable", match_variable)
        pulumi.set(__self__, "selector", selector)
        pulumi.set(__self__, "selector_match_operator", selector_match_operator)

    @_builtins.property
    @pulumi.getter(name="matchVariable")
    def match_variable(self) -> pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionMatchVariable']]:
        """
        The variable type to be excluded.
        """
        return pulumi.get(self, "match_variable")

    @match_variable.setter
    def match_variable(self, value: pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionMatchVariable']]):
        pulumi.set(self, "match_variable", value)

    @_builtins.property
    @pulumi.getter
    def selector(self) -> pulumi.Input[_builtins.str]:
        """
        Selector value for which elements in the collection this exclusion applies to.
        """
        return pulumi.get(self, "selector")

    @selector.setter
    def selector(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "selector", value)

    @_builtins.property
    @pulumi.getter(name="selectorMatchOperator")
    def selector_match_operator(self) -> pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionSelectorMatchOperator']]:
        """
        Comparison operator to apply to the selector when specifying which elements in the collection this exclusion applies to.
        """
        return pulumi.get(self, "selector_match_operator")

    @selector_match_operator.setter
    def selector_match_operator(self, value: pulumi.Input[Union[_builtins.str, 'ManagedRuleExclusionSelectorMatchOperator']]):
        pulumi.set(self, "selector_match_operator", value)


class ManagedRuleGroupOverrideArgsDict(TypedDict):
    """
    Defines a managed rule group override setting.
    """
    rule_group_name: pulumi.Input[_builtins.str]
    """
    Describes the managed rule group to override.
    """
    exclusions: NotRequired[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgsDict']]]]
    """
    Describes the exclusions that are applied to all rules in the group.
    """
    rules: NotRequired[pulumi.Input[Sequence[pulumi.Input['ManagedRuleOverrideArgsDict']]]]
    """
    List of rules that will be disabled. If none specified, all rules in the group will be disabled.
    """

@pulumi.input_type
class ManagedRuleGroupOverrideArgs:
    def __init__(__self__, *,
                 rule_group_name: pulumi.Input[_builtins.str],
                 exclusions: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]] = None,
                 rules: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleOverrideArgs']]]] = None):
        """
        Defines a managed rule group override setting.

        :param pulumi.Input[_builtins.str] rule_group_name: Describes the managed rule group to override.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]] exclusions: Describes the exclusions that are applied to all rules in the group.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedRuleOverrideArgs']]] rules: List of rules that will be disabled. If none specified, all rules in the group will be disabled.
        """
        pulumi.set(__self__, "rule_group_name", rule_group_name)
        if exclusions is not None:
            pulumi.set(__self__, "exclusions", exclusions)
        if rules is not None:
            pulumi.set(__self__, "rules", rules)

    @_builtins.property
    @pulumi.getter(name="ruleGroupName")
    def rule_group_name(self) -> pulumi.Input[_builtins.str]:
        """
        Describes the managed rule group to override.
        """
        return pulumi.get(self, "rule_group_name")

    @rule_group_name.setter
    def rule_group_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rule_group_name", value)

    @_builtins.property
    @pulumi.getter
    def exclusions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]]:
        """
        Describes the exclusions that are applied to all rules in the group.
        """
        return pulumi.get(self, "exclusions")

    @exclusions.setter
    def exclusions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]]):
        pulumi.set(self, "exclusions", value)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleOverrideArgs']]]]:
        """
        List of rules that will be disabled. If none specified, all rules in the group will be disabled.
        """
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleOverrideArgs']]]]):
        pulumi.set(self, "rules", value)


class ManagedRuleOverrideArgsDict(TypedDict):
    """
    Defines a managed rule group override setting.
    """
    rule_id: pulumi.Input[_builtins.str]
    """
    Identifier for the managed rule.
    """
    action: NotRequired[pulumi.Input[Union[_builtins.str, 'ActionType']]]
    """
    Describes the override action to be applied when rule matches.
    """
    enabled_state: NotRequired[pulumi.Input[Union[_builtins.str, 'ManagedRuleEnabledState']]]
    """
    Describes if the managed rule is in enabled or disabled state. Defaults to Disabled if not specified.
    """
    exclusions: NotRequired[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgsDict']]]]
    """
    Describes the exclusions that are applied to this specific rule.
    """

@pulumi.input_type
class ManagedRuleOverrideArgs:
    def __init__(__self__, *,
                 rule_id: pulumi.Input[_builtins.str],
                 action: Optional[pulumi.Input[Union[_builtins.str, 'ActionType']]] = None,
                 enabled_state: Optional[pulumi.Input[Union[_builtins.str, 'ManagedRuleEnabledState']]] = None,
                 exclusions: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]] = None):
        """
        Defines a managed rule group override setting.

        :param pulumi.Input[_builtins.str] rule_id: Identifier for the managed rule.
        :param pulumi.Input[Union[_builtins.str, 'ActionType']] action: Describes the override action to be applied when rule matches.
        :param pulumi.Input[Union[_builtins.str, 'ManagedRuleEnabledState']] enabled_state: Describes if the managed rule is in enabled or disabled state. Defaults to Disabled if not specified.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]] exclusions: Describes the exclusions that are applied to this specific rule.
        """
        pulumi.set(__self__, "rule_id", rule_id)
        if action is not None:
            pulumi.set(__self__, "action", action)
        if enabled_state is not None:
            pulumi.set(__self__, "enabled_state", enabled_state)
        if exclusions is not None:
            pulumi.set(__self__, "exclusions", exclusions)

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> pulumi.Input[_builtins.str]:
        """
        Identifier for the managed rule.
        """
        return pulumi.get(self, "rule_id")

    @rule_id.setter
    def rule_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rule_id", value)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[Union[_builtins.str, 'ActionType']]]:
        """
        Describes the override action to be applied when rule matches.
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[Union[_builtins.str, 'ActionType']]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="enabledState")
    def enabled_state(self) -> Optional[pulumi.Input[Union[_builtins.str, 'ManagedRuleEnabledState']]]:
        """
        Describes if the managed rule is in enabled or disabled state. Defaults to Disabled if not specified.
        """
        return pulumi.get(self, "enabled_state")

    @enabled_state.setter
    def enabled_state(self, value: Optional[pulumi.Input[Union[_builtins.str, 'ManagedRuleEnabledState']]]):
        pulumi.set(self, "enabled_state", value)

    @_builtins.property
    @pulumi.getter
    def exclusions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]]:
        """
        Describes the exclusions that are applied to this specific rule.
        """
        return pulumi.get(self, "exclusions")

    @exclusions.setter
    def exclusions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]]):
        pulumi.set(self, "exclusions", value)


class ManagedRuleSetListArgsDict(TypedDict):
    """
    Defines the list of managed rule sets for the policy.
    """
    managed_rule_sets: NotRequired[pulumi.Input[Sequence[pulumi.Input['ManagedRuleSetArgsDict']]]]
    """
    List of rule sets.
    """

@pulumi.input_type
class ManagedRuleSetListArgs:
    def __init__(__self__, *,
                 managed_rule_sets: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleSetArgs']]]] = None):
        """
        Defines the list of managed rule sets for the policy.

        :param pulumi.Input[Sequence[pulumi.Input['ManagedRuleSetArgs']]] managed_rule_sets: List of rule sets.
        """
        if managed_rule_sets is not None:
            pulumi.set(__self__, "managed_rule_sets", managed_rule_sets)

    @_builtins.property
    @pulumi.getter(name="managedRuleSets")
    def managed_rule_sets(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleSetArgs']]]]:
        """
        List of rule sets.
        """
        return pulumi.get(self, "managed_rule_sets")

    @managed_rule_sets.setter
    def managed_rule_sets(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleSetArgs']]]]):
        pulumi.set(self, "managed_rule_sets", value)


class ManagedRuleSetArgsDict(TypedDict):
    """
    Defines a managed rule set.
    """
    rule_set_type: pulumi.Input[_builtins.str]
    """
    Defines the rule set type to use.
    """
    rule_set_version: pulumi.Input[_builtins.str]
    """
    Defines the version of the rule set to use.
    """
    exclusions: NotRequired[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgsDict']]]]
    """
    Describes the exclusions that are applied to all rules in the set.
    """
    rule_group_overrides: NotRequired[pulumi.Input[Sequence[pulumi.Input['ManagedRuleGroupOverrideArgsDict']]]]
    """
    Defines the rule group overrides to apply to the rule set.
    """
    rule_set_action: NotRequired[pulumi.Input[Union[_builtins.str, 'ManagedRuleSetActionType']]]
    """
    Defines the rule set action.
    """

@pulumi.input_type
class ManagedRuleSetArgs:
    def __init__(__self__, *,
                 rule_set_type: pulumi.Input[_builtins.str],
                 rule_set_version: pulumi.Input[_builtins.str],
                 exclusions: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]] = None,
                 rule_group_overrides: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleGroupOverrideArgs']]]] = None,
                 rule_set_action: Optional[pulumi.Input[Union[_builtins.str, 'ManagedRuleSetActionType']]] = None):
        """
        Defines a managed rule set.

        :param pulumi.Input[_builtins.str] rule_set_type: Defines the rule set type to use.
        :param pulumi.Input[_builtins.str] rule_set_version: Defines the version of the rule set to use.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]] exclusions: Describes the exclusions that are applied to all rules in the set.
        :param pulumi.Input[Sequence[pulumi.Input['ManagedRuleGroupOverrideArgs']]] rule_group_overrides: Defines the rule group overrides to apply to the rule set.
        :param pulumi.Input[Union[_builtins.str, 'ManagedRuleSetActionType']] rule_set_action: Defines the rule set action.
        """
        pulumi.set(__self__, "rule_set_type", rule_set_type)
        pulumi.set(__self__, "rule_set_version", rule_set_version)
        if exclusions is not None:
            pulumi.set(__self__, "exclusions", exclusions)
        if rule_group_overrides is not None:
            pulumi.set(__self__, "rule_group_overrides", rule_group_overrides)
        if rule_set_action is not None:
            pulumi.set(__self__, "rule_set_action", rule_set_action)

    @_builtins.property
    @pulumi.getter(name="ruleSetType")
    def rule_set_type(self) -> pulumi.Input[_builtins.str]:
        """
        Defines the rule set type to use.
        """
        return pulumi.get(self, "rule_set_type")

    @rule_set_type.setter
    def rule_set_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rule_set_type", value)

    @_builtins.property
    @pulumi.getter(name="ruleSetVersion")
    def rule_set_version(self) -> pulumi.Input[_builtins.str]:
        """
        Defines the version of the rule set to use.
        """
        return pulumi.get(self, "rule_set_version")

    @rule_set_version.setter
    def rule_set_version(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "rule_set_version", value)

    @_builtins.property
    @pulumi.getter
    def exclusions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]]:
        """
        Describes the exclusions that are applied to all rules in the set.
        """
        return pulumi.get(self, "exclusions")

    @exclusions.setter
    def exclusions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleExclusionArgs']]]]):
        pulumi.set(self, "exclusions", value)

    @_builtins.property
    @pulumi.getter(name="ruleGroupOverrides")
    def rule_group_overrides(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleGroupOverrideArgs']]]]:
        """
        Defines the rule group overrides to apply to the rule set.
        """
        return pulumi.get(self, "rule_group_overrides")

    @rule_group_overrides.setter
    def rule_group_overrides(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ManagedRuleGroupOverrideArgs']]]]):
        pulumi.set(self, "rule_group_overrides", value)

    @_builtins.property
    @pulumi.getter(name="ruleSetAction")
    def rule_set_action(self) -> Optional[pulumi.Input[Union[_builtins.str, 'ManagedRuleSetActionType']]]:
        """
        Defines the rule set action.
        """
        return pulumi.get(self, "rule_set_action")

    @rule_set_action.setter
    def rule_set_action(self, value: Optional[pulumi.Input[Union[_builtins.str, 'ManagedRuleSetActionType']]]):
        pulumi.set(self, "rule_set_action", value)


class MatchConditionArgsDict(TypedDict):
    """
    Define a match condition.
    """
    match_value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
    """
    List of possible match values.
    """
    match_variable: pulumi.Input[Union[_builtins.str, 'MatchVariable']]
    """
    Request variable to compare with.
    """
    operator: pulumi.Input[Union[_builtins.str, 'Operator']]
    """
    Comparison type to use for matching with the variable value.
    """
    negate_condition: NotRequired[pulumi.Input[_builtins.bool]]
    """
    Describes if the result of this condition should be negated.
    """
    selector: NotRequired[pulumi.Input[_builtins.str]]
    """
    Match against a specific key from the QueryString, PostArgs, RequestHeader or Cookies variables. Default is null.
    """
    transforms: NotRequired[pulumi.Input[Sequence[pulumi.Input[Union[_builtins.str, 'TransformType']]]]]
    """
    List of transforms.
    """

@pulumi.input_type
class MatchConditionArgs:
    def __init__(__self__, *,
                 match_value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 match_variable: pulumi.Input[Union[_builtins.str, 'MatchVariable']],
                 operator: pulumi.Input[Union[_builtins.str, 'Operator']],
                 negate_condition: Optional[pulumi.Input[_builtins.bool]] = None,
                 selector: Optional[pulumi.Input[_builtins.str]] = None,
                 transforms: Optional[pulumi.Input[Sequence[pulumi.Input[Union[_builtins.str, 'TransformType']]]]] = None):
        """
        Define a match condition.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] match_value: List of possible match values.
        :param pulumi.Input[Union[_builtins.str, 'MatchVariable']] match_variable: Request variable to compare with.
        :param pulumi.Input[Union[_builtins.str, 'Operator']] operator: Comparison type to use for matching with the variable value.
        :param pulumi.Input[_builtins.bool] negate_condition: Describes if the result of this condition should be negated.
        :param pulumi.Input[_builtins.str] selector: Match against a specific key from the QueryString, PostArgs, RequestHeader or Cookies variables. Default is null.
        :param pulumi.Input[Sequence[pulumi.Input[Union[_builtins.str, 'TransformType']]]] transforms: List of transforms.
        """
        pulumi.set(__self__, "match_value", match_value)
        pulumi.set(__self__, "match_variable", match_variable)
        pulumi.set(__self__, "operator", operator)
        if negate_condition is not None:
            pulumi.set(__self__, "negate_condition", negate_condition)
        if selector is not None:
            pulumi.set(__self__, "selector", selector)
        if transforms is not None:
            pulumi.set(__self__, "transforms", transforms)

    @_builtins.property
    @pulumi.getter(name="matchValue")
    def match_value(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        List of possible match values.
        """
        return pulumi.get(self, "match_value")

    @match_value.setter
    def match_value(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "match_value", value)

    @_builtins.property
    @pulumi.getter(name="matchVariable")
    def match_variable(self) -> pulumi.Input[Union[_builtins.str, 'MatchVariable']]:
        """
        Request variable to compare with.
        """
        return pulumi.get(self, "match_variable")

    @match_variable.setter
    def match_variable(self, value: pulumi.Input[Union[_builtins.str, 'MatchVariable']]):
        pulumi.set(self, "match_variable", value)

    @_builtins.property
    @pulumi.getter
    def operator(self) -> pulumi.Input[Union[_builtins.str, 'Operator']]:
        """
        Comparison type to use for matching with the variable value.
        """
        return pulumi.get(self, "operator")

    @operator.setter
    def operator(self, value: pulumi.Input[Union[_builtins.str, 'Operator']]):
        pulumi.set(self, "operator", value)

    @_builtins.property
    @pulumi.getter(name="negateCondition")
    def negate_condition(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Describes if the result of this condition should be negated.
        """
        return pulumi.get(self, "negate_condition")

    @negate_condition.setter
    def negate_condition(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "negate_condition", value)

    @_builtins.property
    @pulumi.getter
    def selector(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Match against a specific key from the QueryString, PostArgs, RequestHeader or Cookies variables. Default is null.
        """
        return pulumi.get(self, "selector")

    @selector.setter
    def selector(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "selector", value)

    @_builtins.property
    @pulumi.getter
    def transforms(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[Union[_builtins.str, 'TransformType']]]]]:
        """
        List of transforms.
        """
        return pulumi.get(self, "transforms")

    @transforms.setter
    def transforms(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[Union[_builtins.str, 'TransformType']]]]]):
        pulumi.set(self, "transforms", value)


class PolicySettingsArgsDict(TypedDict):
    """
    Defines top-level WebApplicationFirewallPolicy configuration settings.
    """
    custom_block_response_body: NotRequired[pulumi.Input[_builtins.str]]
    """
    If the action type is block, customer can override the response body. The body must be specified in base64 encoding.
    """
    custom_block_response_status_code: NotRequired[pulumi.Input[_builtins.int]]
    """
    If the action type is block, customer can override the response status code.
    """
    enabled_state: NotRequired[pulumi.Input[Union[_builtins.str, 'PolicyEnabledState']]]
    """
    Describes if the policy is in enabled or disabled state. Defaults to Enabled if not specified.
    """
    javascript_challenge_expiration_in_minutes: NotRequired[pulumi.Input[_builtins.int]]
    """
    Defines the JavaScript challenge cookie validity lifetime in minutes. This setting is only applicable to Premium_AzureFrontDoor. Value must be an integer between 5 and 1440 with the default value being 30.
    """
    mode: NotRequired[pulumi.Input[Union[_builtins.str, 'PolicyMode']]]
    """
    Describes if it is in detection mode or prevention mode at policy level.
    """
    redirect_url: NotRequired[pulumi.Input[_builtins.str]]
    """
    If action type is redirect, this field represents redirect URL for the client.
    """
    request_body_check: NotRequired[pulumi.Input[Union[_builtins.str, 'PolicyRequestBodyCheck']]]
    """
    Describes if policy managed rules will inspect the request body content.
    """
    scrubbing_rules: NotRequired[pulumi.Input[Sequence[pulumi.Input['WebApplicationFirewallScrubbingRulesArgsDict']]]]
    """
    List of log scrubbing rules applied to the Web Application Firewall logs.
    """
    state: NotRequired[pulumi.Input[Union[_builtins.str, 'WebApplicationFirewallScrubbingState']]]
    """
    State of the log scrubbing config. Default value is Enabled.
    """

@pulumi.input_type
class PolicySettingsArgs:
    def __init__(__self__, *,
                 custom_block_response_body: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_block_response_status_code: Optional[pulumi.Input[_builtins.int]] = None,
                 enabled_state: Optional[pulumi.Input[Union[_builtins.str, 'PolicyEnabledState']]] = None,
                 javascript_challenge_expiration_in_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 mode: Optional[pulumi.Input[Union[_builtins.str, 'PolicyMode']]] = None,
                 redirect_url: Optional[pulumi.Input[_builtins.str]] = None,
                 request_body_check: Optional[pulumi.Input[Union[_builtins.str, 'PolicyRequestBodyCheck']]] = None,
                 scrubbing_rules: Optional[pulumi.Input[Sequence[pulumi.Input['WebApplicationFirewallScrubbingRulesArgs']]]] = None,
                 state: Optional[pulumi.Input[Union[_builtins.str, 'WebApplicationFirewallScrubbingState']]] = None):
        """
        Defines top-level WebApplicationFirewallPolicy configuration settings.

        :param pulumi.Input[_builtins.str] custom_block_response_body: If the action type is block, customer can override the response body. The body must be specified in base64 encoding.
        :param pulumi.Input[_builtins.int] custom_block_response_status_code: If the action type is block, customer can override the response status code.
        :param pulumi.Input[Union[_builtins.str, 'PolicyEnabledState']] enabled_state: Describes if the policy is in enabled or disabled state. Defaults to Enabled if not specified.
        :param pulumi.Input[_builtins.int] javascript_challenge_expiration_in_minutes: Defines the JavaScript challenge cookie validity lifetime in minutes. This setting is only applicable to Premium_AzureFrontDoor. Value must be an integer between 5 and 1440 with the default value being 30.
        :param pulumi.Input[Union[_builtins.str, 'PolicyMode']] mode: Describes if it is in detection mode or prevention mode at policy level.
        :param pulumi.Input[_builtins.str] redirect_url: If action type is redirect, this field represents redirect URL for the client.
        :param pulumi.Input[Union[_builtins.str, 'PolicyRequestBodyCheck']] request_body_check: Describes if policy managed rules will inspect the request body content.
        :param pulumi.Input[Sequence[pulumi.Input['WebApplicationFirewallScrubbingRulesArgs']]] scrubbing_rules: List of log scrubbing rules applied to the Web Application Firewall logs.
        :param pulumi.Input[Union[_builtins.str, 'WebApplicationFirewallScrubbingState']] state: State of the log scrubbing config. Default value is Enabled.
        """
        if custom_block_response_body is not None:
            pulumi.set(__self__, "custom_block_response_body", custom_block_response_body)
        if custom_block_response_status_code is not None:
            pulumi.set(__self__, "custom_block_response_status_code", custom_block_response_status_code)
        if enabled_state is not None:
            pulumi.set(__self__, "enabled_state", enabled_state)
        if javascript_challenge_expiration_in_minutes is not None:
            pulumi.set(__self__, "javascript_challenge_expiration_in_minutes", javascript_challenge_expiration_in_minutes)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if redirect_url is not None:
            pulumi.set(__self__, "redirect_url", redirect_url)
        if request_body_check is not None:
            pulumi.set(__self__, "request_body_check", request_body_check)
        if scrubbing_rules is not None:
            pulumi.set(__self__, "scrubbing_rules", scrubbing_rules)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @_builtins.property
    @pulumi.getter(name="customBlockResponseBody")
    def custom_block_response_body(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        If the action type is block, customer can override the response body. The body must be specified in base64 encoding.
        """
        return pulumi.get(self, "custom_block_response_body")

    @custom_block_response_body.setter
    def custom_block_response_body(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "custom_block_response_body", value)

    @_builtins.property
    @pulumi.getter(name="customBlockResponseStatusCode")
    def custom_block_response_status_code(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        If the action type is block, customer can override the response status code.
        """
        return pulumi.get(self, "custom_block_response_status_code")

    @custom_block_response_status_code.setter
    def custom_block_response_status_code(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "custom_block_response_status_code", value)

    @_builtins.property
    @pulumi.getter(name="enabledState")
    def enabled_state(self) -> Optional[pulumi.Input[Union[_builtins.str, 'PolicyEnabledState']]]:
        """
        Describes if the policy is in enabled or disabled state. Defaults to Enabled if not specified.
        """
        return pulumi.get(self, "enabled_state")

    @enabled_state.setter
    def enabled_state(self, value: Optional[pulumi.Input[Union[_builtins.str, 'PolicyEnabledState']]]):
        pulumi.set(self, "enabled_state", value)

    @_builtins.property
    @pulumi.getter(name="javascriptChallengeExpirationInMinutes")
    def javascript_challenge_expiration_in_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Defines the JavaScript challenge cookie validity lifetime in minutes. This setting is only applicable to Premium_AzureFrontDoor. Value must be an integer between 5 and 1440 with the default value being 30.
        """
        return pulumi.get(self, "javascript_challenge_expiration_in_minutes")

    @javascript_challenge_expiration_in_minutes.setter
    def javascript_challenge_expiration_in_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "javascript_challenge_expiration_in_minutes", value)

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[pulumi.Input[Union[_builtins.str, 'PolicyMode']]]:
        """
        Describes if it is in detection mode or prevention mode at policy level.
        """
        return pulumi.get(self, "mode")

    @mode.setter
    def mode(self, value: Optional[pulumi.Input[Union[_builtins.str, 'PolicyMode']]]):
        pulumi.set(self, "mode", value)

    @_builtins.property
    @pulumi.getter(name="redirectUrl")
    def redirect_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        If action type is redirect, this field represents redirect URL for the client.
        """
        return pulumi.get(self, "redirect_url")

    @redirect_url.setter
    def redirect_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "redirect_url", value)

    @_builtins.property
    @pulumi.getter(name="requestBodyCheck")
    def request_body_check(self) -> Optional[pulumi.Input[Union[_builtins.str, 'PolicyRequestBodyCheck']]]:
        """
        Describes if policy managed rules will inspect the request body content.
        """
        return pulumi.get(self, "request_body_check")

    @request_body_check.setter
    def request_body_check(self, value: Optional[pulumi.Input[Union[_builtins.str, 'PolicyRequestBodyCheck']]]):
        pulumi.set(self, "request_body_check", value)

    @_builtins.property
    @pulumi.getter(name="scrubbingRules")
    def scrubbing_rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['WebApplicationFirewallScrubbingRulesArgs']]]]:
        """
        List of log scrubbing rules applied to the Web Application Firewall logs.
        """
        return pulumi.get(self, "scrubbing_rules")

    @scrubbing_rules.setter
    def scrubbing_rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['WebApplicationFirewallScrubbingRulesArgs']]]]):
        pulumi.set(self, "scrubbing_rules", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[Union[_builtins.str, 'WebApplicationFirewallScrubbingState']]]:
        """
        State of the log scrubbing config. Default value is Enabled.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[Union[_builtins.str, 'WebApplicationFirewallScrubbingState']]]):
        pulumi.set(self, "state", value)


class SkuArgsDict(TypedDict):
    """
    The pricing tier of the web application firewall policy.
    """
    name: NotRequired[pulumi.Input[Union[_builtins.str, 'SkuName']]]
    """
    Name of the pricing tier.
    """

@pulumi.input_type
class SkuArgs:
    def __init__(__self__, *,
                 name: Optional[pulumi.Input[Union[_builtins.str, 'SkuName']]] = None):
        """
        The pricing tier of the web application firewall policy.

        :param pulumi.Input[Union[_builtins.str, 'SkuName']] name: Name of the pricing tier.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[Union[_builtins.str, 'SkuName']]]:
        """
        Name of the pricing tier.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[Union[_builtins.str, 'SkuName']]]):
        pulumi.set(self, "name", value)


class WebApplicationFirewallScrubbingRulesArgsDict(TypedDict):
    """
    Defines the contents of the log scrubbing rules.
    """
    match_variable: pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchVariable']]
    """
    The variable to be scrubbed from the logs.
    """
    selector_match_operator: pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchOperator']]
    """
    When matchVariable is a collection, operate on the selector to specify which elements in the collection this rule applies to.
    """
    selector: NotRequired[pulumi.Input[_builtins.str]]
    """
    When matchVariable is a collection, operator used to specify which elements in the collection this rule applies to.
    """
    state: NotRequired[pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryState']]]
    """
    Defines the state of a log scrubbing rule. Default value is enabled.
    """

@pulumi.input_type
class WebApplicationFirewallScrubbingRulesArgs:
    def __init__(__self__, *,
                 match_variable: pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchVariable']],
                 selector_match_operator: pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchOperator']],
                 selector: Optional[pulumi.Input[_builtins.str]] = None,
                 state: Optional[pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryState']]] = None):
        """
        Defines the contents of the log scrubbing rules.

        :param pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchVariable']] match_variable: The variable to be scrubbed from the logs.
        :param pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchOperator']] selector_match_operator: When matchVariable is a collection, operate on the selector to specify which elements in the collection this rule applies to.
        :param pulumi.Input[_builtins.str] selector: When matchVariable is a collection, operator used to specify which elements in the collection this rule applies to.
        :param pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryState']] state: Defines the state of a log scrubbing rule. Default value is enabled.
        """
        pulumi.set(__self__, "match_variable", match_variable)
        pulumi.set(__self__, "selector_match_operator", selector_match_operator)
        if selector is not None:
            pulumi.set(__self__, "selector", selector)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @_builtins.property
    @pulumi.getter(name="matchVariable")
    def match_variable(self) -> pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchVariable']]:
        """
        The variable to be scrubbed from the logs.
        """
        return pulumi.get(self, "match_variable")

    @match_variable.setter
    def match_variable(self, value: pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchVariable']]):
        pulumi.set(self, "match_variable", value)

    @_builtins.property
    @pulumi.getter(name="selectorMatchOperator")
    def selector_match_operator(self) -> pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchOperator']]:
        """
        When matchVariable is a collection, operate on the selector to specify which elements in the collection this rule applies to.
        """
        return pulumi.get(self, "selector_match_operator")

    @selector_match_operator.setter
    def selector_match_operator(self, value: pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryMatchOperator']]):
        pulumi.set(self, "selector_match_operator", value)

    @_builtins.property
    @pulumi.getter
    def selector(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        When matchVariable is a collection, operator used to specify which elements in the collection this rule applies to.
        """
        return pulumi.get(self, "selector")

    @selector.setter
    def selector(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "selector", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryState']]]:
        """
        Defines the state of a log scrubbing rule. Default value is enabled.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[Union[_builtins.str, 'ScrubbingRuleEntryState']]]):
        pulumi.set(self, "state", value)


