# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_azure_native_frontdoor_v20240201.config as __config
    config = __config
    import pulumi_azure_native_frontdoor_v20240201.frontdoor as __frontdoor
    frontdoor = __frontdoor
else:
    config = _utilities.lazy_import('pulumi_azure_native_frontdoor_v20240201.config')
    frontdoor = _utilities.lazy_import('pulumi_azure_native_frontdoor_v20240201.frontdoor')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azure-native_frontdoor_v20240201",
  "mod": "frontdoor",
  "fqn": "pulumi_azure_native_frontdoor_v20240201.frontdoor",
  "classes": {
   "azure-native_frontdoor_v20240201:frontdoor:Policy": "Policy"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azure-native_frontdoor_v20240201",
  "token": "pulumi:providers:azure-native_frontdoor_v20240201",
  "fqn": "pulumi_azure_native_frontdoor_v20240201",
  "class": "Provider"
 }
]
"""
)
